name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@master
        with:
          shell-action: swift build --triple wasm32-unknown-wasi --product TokamakDemo

  macos_demo_build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Build macOS installable archive
        shell: bash
        run: |
          set -ex
          sudo xcode-select --switch /Applications/Xcode_12_beta.app/Contents/Developer/
          cd "TokamakDemo Native"
          xcodebuild -scheme macOS
