name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  swiftwasm_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: swiftwasm/swiftwasm-action@v5.3
        with:
          shell-action: carton bundle --product TokamakDemo

  macos_build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Run the test suite on macOS, build the demo project for iOS
        shell: bash
        run: |
          set -ex
          sudo xcode-select --switch /Applications/Xcode_12.2.app/Contents/Developer/
          # avoid building unrelated products for testing by specifying the test product explicitly
          swift build --product TokamakPackageTests
          `xcrun --find xctest` .build/debug/TokamakPackageTests.xctest

          xcodebuild -version
          cd "NativeDemo"
          xcodebuild -scheme iOS -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | \
            xcpretty --color
